trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'arm-svc-con'
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  acrServiceConnection: 'acr-svc-connection'
  aksServiceConnection: 'aks-svc-connection'
  acrName: 'acronlinestoredevuksouth001'
  namespace: 'default'
  environment: "dev"
  artifactName: 'storehelmchart'
  helmChartName: 'mychart'

stages:
  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: HelmPackagePush
    jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: self

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Set Helm OCI support"
            export HELM_EXPERIMENTAL_OCI=1

            echo "Login to ACR"
            az acr login --name ${{ variables.acrName }}

            echo "Login to AKS"
            az aks get-credentials --name $(aksCluster) --resource-group $(aksResourceGroup) --overwrite-existing

            echo "Pull Helm chart from ACR"
            helm pull oci://${{ variables.acrName }}.azurecr.io/helm/${{ variables.helmChartName }} --version ${{ variables.helmChartVersion }} --untar

      - task: HelmDeploy@1
        displayName: Helm Upgrade/Install
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: $(serviceConnection)
          azureResourceGroup: $(aksResourceGroup)
          kubernetesCluster: $(aksCluster)
          namespace: $(namespace)
          command: upgrade
          chartType: FilePath
          chartPath: './mychart/rabbitmq'
          releaseName: 'storeapp'
          install: true
          waitForExecution: true                  