apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}-rabbitmq-enabled-plugins
  labels:
  {{- include "config.labels" . | nindent 4 }}
data:
  rabbitmq_enabled_plugins: {{ .Values.rabbitmqEnabledPlugins.rabbitmqEnabledPlugins
    | toYaml | indent 1 }}
