apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-rabbitmq
  labels:
  {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.type }}
  selector:
    app: rabbitmq
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.rabbitmq.ports | toYaml | nindent 2 }}
